### ISSUE TITLE
Where I am I supposed to insert Volumizer.configure()?

### ISSUE THREAD

**Issue by ghost** [fxwx23/Volumizer#6]
Hi, I'm a little confused about where I am opposed to insert the Volumizer.configure(), I have installed Volumizer using Cocoapods but still receive the error "Use of unresolved identifier 'Volumizer' ".

Thank You.

**Comment by fxwx23** [comment]
Thanks for your issue. @donron2325 
Please make sure that import it first.
```swift
import Volumizer
```
And please do not call `Volumizer.configure()` in `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool`, because the first key window is not visible yet. 
please call it once in `viewDidLoad()` of some viewController is better right now. 

Sorry for not maintaining a long time :(

**Comment by ghost** [comment]
Thank you!

**Comment by ghost** [comment]
Why does the volume bar sometimes not show up? It usually fails to appear after minimizing the app and and re-entering.

**Comment by fxwx23** [comment]
I guess it would be a bug :(
Please report that as another issue with details.
